name: GCP Setup with Service Account

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up 
